import fs from "node:fs";
import path from "node:path";
import pc from "picocolors";
import { discoverFromDir, discoverFromKnownClients } from "../discovery/index.js";
import { scanAll, summarize } from "../scanner/index.js";
import { PolicyStore } from "../sandbox/store.js";
import { isDockerAvailable } from "../sandbox/docker.js";
import { isBubblewrapAvailable } from "../sandbox/bubblewrap.js";
import { rewriteStatus } from "../rewrite/index.js";
import type { ScanResult } from "../types.js";

export interface ReportOptions {
  from?: string;
  stdout?: boolean;
  out?: string;
  /** Stable timestamp for tests so the output is byte-deterministic. */
  now?: string;
}

function badge(level: ScanResult["level"]): string {
  return level === "risky" ? "🔴 risky" : level === "review" ? "🟡 review" : "🟢 trusted";
}

/** Pure markdown builder — easy to test. */
export function buildReport(opts: ReportOptions): string {
  const servers = opts.from ? discoverFromDir(opts.from) : discoverFromKnownClients();
  const policies = new PolicyStore().read();
  const results = scanAll(servers, policies.servers);
  const summary = summarize(results);
  const sortedResults = [...results].sort((a, b) => {
    const rank = (l: ScanResult["level"]): number => (l === "risky" ? 0 : l === "review" ? 1 : 2);
    return rank(a.level) - rank(b.level) || a.server.name.localeCompare(b.server.name);
  });
  const rewrites = rewriteStatus();
  const now = opts.now ?? new Date().toISOString();

  const lines: string[] = [];
  lines.push("# wardn trust report");
  lines.push("");
  lines.push(`_Generated ${now}_`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push("| Metric | Count |");
  lines.push("|---|---:|");
  lines.push(`| Servers | ${summary.total} |`);
  lines.push(`| Risky | ${summary.risky} |`);
  lines.push(`| Review | ${summary.review} |`);
  lines.push(`| Trusted | ${summary.trusted} |`);
  lines.push("");
  lines.push("## Environment");
  lines.push("");
  lines.push(`- Docker available: ${isDockerAvailable() ? "yes" : "no"}`);
  lines.push(`- Bubblewrap available: ${isBubblewrapAvailable() ? "yes" : "no"}`);
  lines.push(`- Active rewrites: ${rewrites.entries.length}`);
  lines.push("");
  lines.push("## Servers");
  lines.push("");
  if (sortedResults.length === 0) {
    lines.push("_No MCP servers discovered._");
  } else {
    lines.push("| Server | Client | Trust | Signals |");
    lines.push("|---|---|---|---|");
    for (const r of sortedResults) {
      const sigs = r.signals.map((s) => "`" + s.id + "`").join(" ") || "—";
      lines.push(`| **${r.server.name}** | ${r.server.client} | ${badge(r.level)} | ${sigs} |`);
    }
  }
  lines.push("");
  lines.push("### Signal reasons");
  lines.push("");
  for (const r of sortedResults) {
    if (r.signals.length === 0) continue;
    lines.push(`- **${r.server.name}** _(${r.server.client})_`);
    for (const s of r.signals) {
      lines.push(`  - \`${s.id}\` (${s.severity}) — ${s.reason}`);
    }
  }
  lines.push("");
  lines.push("## Sandbox policies");
  lines.push("");
  const policyEntries = Object.values(policies.servers);
  if (policyEntries.length === 0) {
    lines.push("_No sandbox policies configured._");
  } else {
    lines.push("| Server | Enabled | Filesystem | Network | Env whitelist |");
    lines.push("|---|---|---|---|---|");
    for (const p of policyEntries) {
      const fs = p.filesystem.paths.length > 0 ? p.filesystem.paths.join("<br/>") : "—";
      const env = p.envWhitelist.length > 0 ? p.envWhitelist.join(", ") : "baseline";
      lines.push(`| **${p.name}** | ${p.enabled ? "yes" : "no"} | ${fs} | ${p.network ? "on" : "off"} | ${env} |`);
    }
  }
  lines.push("");
  lines.push("## Rewrites");
  lines.push("");
  if (rewrites.entries.length === 0) {
    lines.push("_No client configs are routed through wardn yet._");
  } else {
    lines.push("| Client | Config | Servers | When |");
    lines.push("|---|---|---|---|");
    for (const e of rewrites.entries) {
      lines.push(`| ${e.client} | \`${e.configFile}\` | ${e.servers.join(", ") || "—"} | ${e.timestamp} |`);
    }
  }
  lines.push("");
  lines.push("_Generated by `wardn report` — https://github.com/lynuxis2026-pixel/wardn_");
  return lines.join("\n");
}

function defaultReportFile(now: string): string {
  const datePart = now.slice(0, 10);
  return path.join(process.cwd(), `wardn-report-${datePart}.md`);
}

export function runReport(opts: ReportOptions): number {
  const md = buildReport(opts);
  if (opts.stdout) {
    process.stdout.write(md + "\n");
    return 0;
  }
  const out = opts.out ?? defaultReportFile(opts.now ?? new Date().toISOString());
  fs.writeFileSync(out, md + "\n");
  process.stdout.write("\n" + pc.bold("wardn report") + "\n\n");
  process.stdout.write(`  ${pc.green("✓")} ${out}\n\n`);
  return 0;
}
